name: Push Test Workflow

on: 
    push:
        branches: 
            - main

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@main
      
    - name : Install Packages 
      run : |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name : Run tests 
      run : pytest 5_unittest.py
      