name: Push Test Workflow

on: 
    push:
        branches: 
            - main

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@main
      
    - name : Install Packages 
      run : |
        pip install pytest
        pip install requests
        pip install fastapi
        pip install httpx
      
    - name : Run tests 
      run : pytest 5_unittest.py
      